# Generated by Django 3.1.7 on 2021-03-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('time_of_creation', models.DateTimeField(auto_now=True)),
                ('unique_shared_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
