# Generated by Django 3.1.7 on 2021-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_logic', '0002_sharedkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedkey',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
