# Generated by Django 3.1.7 on 2021-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_logic', '0003_sharedkey_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedkey',
            name='time_till_expiration',
            field=models.IntegerField(default=5),
        ),
    ]
